name: Node.js CI

on: [push]

jobs:
  xây dựng :phan microsoft 
Hay nói, là một tài tài của, qua, qua, qua một tài, qua sức, qua một tài
    chạy trên : mới nhất https : //github.com/Android0868/torch.github.io.git 
Hay nói, là một tài tài của, qua, qua, qua một tài, qua sức, qua một tài
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
